name: sagawa_pos_new
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

  # DIO client for API calls
  dio: ^5.9.0

  # State management
  bloc: ^9.1.0
  flutter_bloc: ^9.1.0
  provider: ^6.1.2

  # Environment variables
  flutter_dotenv: ^5.1.0

  # UI components
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0

  # Local storage
  shared_preferences: ^2.2.2

  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3

  # Image processing and display
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  form_field_validator: ^1.1.0
  fluttertoast: ^8.2.8

  # Animations
  lottie: ^3.1.2

  # SVG support
  flutter_svg: ^2.0.10+1

  url_launcher: ^6.3.0

  # Supabase
  image_picker: ^1.1.2
  supabase_flutter: ^2.10.3

  # Splash screen
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/element/
    - assets/icons/
    - assets/animations/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/ic_launcher.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo/logo_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo/logo_pos.png
  
  color_dark: "#FFFFFF"
  image_dark: assets/logo/logo_pos.png
  
  android_12:
    image: assets/logo/logo_pos.png
    icon_background_color: "#FFFFFF"
    
  android: true
  ios: true
  web: false
  
  android_gravity: center
  ios_content_mode: center
  
  fullscreen: true
  
  info_plist_files:
    - 'ios/Runner/Info.plist'