name: sagawa_pos
description: "Aplikasi kasir untuk pemesanan makanan sagawagroup"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons.
  cupertino_icons: ^1.0.8
  
  # DIO client for API calls
  dio: ^5.9.0
  
  # State management
  bloc: ^9.1.0
  flutter_bloc: ^9.1.0
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # UI components
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3

  # Image processing and display
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1
  form_field_validator: ^1.1.0
  fluttertoast: ^9.0.0

  # Supabase
  image_picker: ^1.2.0
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  
  assets:
    - .env
    - assets/